config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root：最初のルーティングを定義する
  root 'home#index'

  # 明示的なルーティング指定
  get 'mypage', to: 'users#me'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # リソースベースルーティング：コントローラーの7つのアクションをまとめて定義する
  # resource：単数形リソースを使用してルーティングを定義
  # resources：複数形リソースを使用してルーティングを定義
  # only：必要なルーティングのみに絞る
  resources :users, only: %i[new create update]
  resources :boards
  resources :comments, only: %i[create destroy]
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  body       :text(65535)
#  name       :string(255)
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Board < ApplicationRecord
  # has_many :through：多対多のつながりを設定。2つのモデルの間に第3のモデルが介在する。
  # dependent：オーナーオブジェクトがdestroyされたときに、オーナーに関連付けられたオブジェクトをどうするかを制御する。
  has_many :comments, dependent: :delete_all
  has_many :board_tag_relations, dependent: :delete_all
  has_many :tags, through: :board_tag_relations

  # validates：Active Recordの検証機能。
  #  presence：指定された属性が「空でない」ことを確認する。
  #  length：属性の値の長さを検証する。
  validates :name, presence: true, length: { maximum: 10 }
  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 1000 }
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # onlyで絞り込んだアクションの直前にset_target_boardを実行する
  before_action :set_target_board, only: %i[show edit update destroy]

  # 掲示板一覧画面の表示
  def index
    # ※三項演算子で記述（条件式 ? もし値があった場合:もし値がなかった場合）
    #
    # params[:tag_id].present?：tag_idが取得できるかどうか。
    #   取得できた場合 → tag_idからタグを検索してタグに紐づく掲示板の一覧を取得する
    #   取得できなかった場合 → 掲示板の一覧を取得する
    #
    #   （@boardの中身が参照されてからDBに取得しにいくため、この時点ではDBにアクセスしていない）
    @boards = params[:tag_id].present? ? Tag.find(params[:tag_id]).boards : Board.all
    # page：引数に指定したページに表示するデータのみを取得する（デフォルトは25件）
    # @boardが参照されたため、DBに対して1ページあたりの掲示板の表示件数である10件に制限されたSQLが発行される
    @boards = @boards.page(params[:page])
  end

  # 掲示板新規作成画面の表示
  def new
    # Boardオブジェクトをインスタンス変数に格納する
    # コントローラー内で定義したインスタンス変数はビューで参照できる
    # 下記で掲示板作成に失敗した場合、flashで返されたBoardオブジェクトの内容をフォームに表示する
    @board = Board.new(flash[:board])
  end

  # 掲示板作成
  def create
    # StrongParametersで取得した値でBoardオブジェクト初期化して、ローカル変数に格納する
    board = Board.new(board_params)
    # DBにコミットする
    if board.save
      # コミット成功：flashでメッセージを返して掲示板画面にリダイレクトする
      flash[:notice] = "「#{board.title}」の掲示板を作成しました"
      redirect_to board
    else
      # コミット失敗：flashでBoardオブジェクトとエラーメッセージを返して掲示板新規作成画面にリダイレクトする
      redirect_to new_board_path, flash: {
        board: board,
        error_messages: board.errors.full_messages
      }
    end
  end

  # 掲示板詳細画面を表示
  def show
    # board_idを指定してCommentオブジェクトを作成し、インスタンス変数に格納する
    # @comment = @board.comments.newとすると空のコメントがcommentsに含まれてしまうためNG
    @comment = Comment.new(board_id: @board.id)
  end

  # 掲示板編集画面を表示
  def edit; end

  # 掲示板の内容を更新
  def update
    # StrongParametersで取得した値に更新してDBにコミットする
    if @board.update(board_params)
      # コミット成功：flashでメッセージを返して掲示板詳細画面にリダイレクトする
      flash[:notice] = "「#{@board.title}」の掲示板を修正しました"
      redirect_to @board # オブジェクトを指定することで/boards/:idのパスにリダイレクトされる
    else
      # コミット失敗：flashでBoardオブジェクトとエラーメッセージを返して掲示板編集画面にリダイレクトする
      redirect_back fallback_location: root_path, flash: {
        board: @board,
        error_messages: @board.errors.full_messages
      }
    end
  end

  # 掲示板を削除
  def destroy
    # オブジェクトをDBから削除する
    @board.destroy
    # flashでメッセージを返して掲示板一覧画面にリダイレクトする
    redirect_to boards_path, flash: { notice: "「#{@board.title}」の掲示板が削除されました" }
  end

  # 許可するパラメータはprivateメソッドでカプセル化する
  # createとupdateの両方で使いまわすことができる
  private

  # StrongPrameters
  #  require：POSTで受け取る値のキーを設定
  #  permit：許可するカラム指定
  def board_params
    params.require(:board).permit(:name, :title, :body, tag_ids: [])
  end

  # idを元にBoardモデルから該当のデータを1つ取得する
  def set_target_board
    @board = Board.find(params[:id])
  end
end

app/views/boards/_board.html.erb
<div class="card">
    <div class="card-header">
        <h4><%= board.title %></h4>
        <% board.tags.each do |tag| %>
        <span class="badge badge-primary"><%= tag.name %></span>
        <% end %>
    </div>
    <div class="card-body">
        <p class="card-text"><%= simple_format(board.body) %></p>
        <p class="text-right font-weight-bold mr-10"><%= board.name %></p>
    </div>
</div>

app/views/boards/_form.html.erb
<%= render 'shared/error_messages' %>

<%= form_with model: board do |f| %>
<div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
    <%= f.label :body, '本文' %>
    <%= f.text_area :body, class: 'form-control', rows: 10 %>
</div>
<div class="form-group">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
    <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
        <%= tag.check_box class: 'form-check-input' %>
        <%= tag.text %>
        <% end %>
    </div>
    <% end %>
</div>

<%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/boards/edit.html.erb
<div class="d-flex align-items-center">
    <h1>掲示板編集</h1>
    <div class="ml-auto boards__linkBox">
        <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
    </div>
</div>
<%= render partial: 'form', locals: { board: @board} %>

app/views/boards/index.html.erb
<div class="d-flex align-items-center">
  <h1>掲示板一覧</h1>
  <div class="ml-auto boards__linkBox">
    <%= form_with url: boards_path, method: :get, class: 'boards__searchForm' do %>
    <%= select_tag :tag_id,
                   options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
                   {
                     prompt: 'タグで絞り込み',
                     class: 'form-control boards__select',
                     onchange: 'submit(this.form);'
                   }
    %>
    <% end %>
    <%= link_to '新規作成', new_board_path, class: 'btn btn-outline-dark' %>
  </div>
</div>

<% if flash[:notice] %>
<div class="alert alert-danger"><%= flash[:notice] %></div>
<% end %>

<table class="table table-hover boards__table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>作成者</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
    <tr>
      <td><%= board.id %></td>
      <td><%= board.title %></td>
      <td><%= board.name %></td>
      <td><%= board.created_at.to_s(:datetime_jp) %></td>
      <td><%= board.updated_at.to_s(:datetime_jp) %></td>
      <td><%= link_to '詳細', board, class: 'btn btn-outline-dark' %></td>
      <td><%= link_to '削除', board, class: 'btn btn-outline-dark', method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%# ページネーションのリンク %>
<%= paginate @boards %>

app/views/boards/new.html.erb
<div class="d-flex align-items-center">
    <h1>掲示板作成</h1>
    <div class="ml-auto boards__linkBox">
        <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
    </div>
</div>
<%= render partial: 'form', locals: { board: @board} %>

app/views/boards/show.html.erb
<div class="d-flex align-items-center mt-4 mb-4">
    <div class="ml-auto boards__linkBox">
        <%= link_to '一覧', boards_path, class: 'btn btn-outline-dark' %>
        <%= link_to '編集', edit_board_path(@board), class: 'btn btn-outline-dark' %>
    </div>
</div>

<% if flash[:notice] %>
<div class="alert alert-primary"><%= flash[:notice] %></div>
<% end %>

<%# モデルオブジェクトのページを表示だけの場合、render @boardのみでもOK %>
<%= render @board %>

<div class="p-comment__list">
    <div class="p-comment__listTitle">コメント</div>
    <%= render @board.comments %>
</div>


<%= render partial: 'comments/form', locals: { comment: @comment } %>