config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root：最初のルーティングを定義する
  root 'home#index'

  # 明示的なルーティング指定
  get 'mypage', to: 'users#me'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # リソースベースルーティング：コントローラーの7つのアクションをまとめて定義する
  # resource：単数形リソースを使用してルーティングを定義
  # resources：複数形リソースを使用してルーティングを定義
  # only：必要なルーティングのみに絞る
  resources :users, only: %i[new create update]
  resources :boards
  resources :comments, only: %i[create destroy]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # CSRF対応
  protect_from_forgery with: :exception
  # ApplicationControllerはすべてのコントローラーで継承されているため、
  # すべてのアクションの実行前にcurrent_userメソッドを実行する
  before_action :current_user

  private

  # ログイン中のユーザーを取得
  def current_user
    # セッションにuser.idが保存されていなければリターンする
    return unless session[:user_id]

    # セッションに保存されているuser.idに一致するユーザーをUserモデルから取得してインスタンス変数に格納する
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/helpers/application_helper.rb
# 全ページで使用されるヘルパーを定義
module ApplicationHelper
  # ナビゲーションバー 表示切替（name:リンクの表示名、path:リンク先のパス）
  def header_link_item(name, path)
    # classに'nav-item'を追加
    class_name = 'nav-item'
    # 表示中のページとリンク先のパスが同じであればリンクの表示をアクティブにする
    class_name << ' active' if current_page?(path)

    # 任意のhtmlタグを作成する（:liタグの作成、:上記で作成したclass名を指定）
    # ネストさせているので<li><a/></li>のようなかたちになる
    content_tag :li, class: class_name do
      link_to name, path, class: 'nav-link'
    end
  end
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">BoardApp</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <%= header_link_item('ホーム', root_path) %>
            </li>
            <li class="nav-item">
                <%= header_link_item('掲示板一覧', boards_path) %>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    ユーザー
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <% if @current_user %>
                    <%= link_to 'マイページ', mypage_path, class: 'dropdown-item' %>
                    <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
                    <% else %>
                    <%= link_to '登録', new_user_path, class: 'dropdown-item' %>
                    <%= link_to 'ログイン', root_path, class: 'dropdown-item' %>
                    <% end %>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>